"""empty message

Revision ID: 038641804495
Revises: 9db6068cbf52
Create Date: 2026-04-08 01:57:47.290471

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '038641804495'
down_revision = '9db6068cbf52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_dark_triads', 'cynicism',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='0=глубокая вера в доброту людей → 1=циничный, недоверие к мотивам людей',
               existing_nullable=True)
    op.alter_column('user_dark_triads', 'narcissism',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Нарциссизм: 0=скромный → 1=самолюбование, грандиозность',
               existing_nullable=True)
    op.alter_column('user_dark_triads', 'machiavellianism',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Макиавеллизм: 0=прямой и честный → 1=манипулятивный, хитрый',
               existing_nullable=True)
    op.alter_column('user_dark_triads', 'psychoticism',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Психотизм: 0=нормальность, эмпатия → 1=холодность, необычный опыт',
               existing_nullable=True)
    op.add_column('users', sa.Column('passed_personality_core', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='типирование personality_core пройдено'))
    op.add_column('users', sa.Column('passed_holland', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='типирование holland пройдено'))
    op.add_column('users', sa.Column('passed_neurodiversity', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='типирование neurodiversity пройдено'))
    op.add_column('users', sa.Column('passed_mood_anxiety', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='типирование mood_anxiety пройдено'))
    op.add_column('users', sa.Column('passed_body_image_eating', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='типирование body_image_eating пройдено'))
    op.add_column('users', sa.Column('passed_sex_romance', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='типирование sex_romance пройдено'))
    op.alter_column('users', 'gender',
               existing_type=postgresql.ENUM('male', 'girl', 'neutral', name='gender'),
               comment='гендер',
               existing_comment='gender',
               existing_nullable=False,
               existing_server_default=sa.text("'male'::gender"))
    op.drop_column('users', 'love_access')
    op.drop_column('users', 'dark_triads_full')
    op.drop_column('users', 'clinical_access')
    op.drop_column('users', 'passed_typing')
    op.drop_column('users', 'humor_access')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('humor_access', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='базовая характеристика доступ'))
    op.add_column('users', sa.Column('passed_typing', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='типирование пройдено'))
    op.add_column('users', sa.Column('clinical_access', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='клиническая характеристика доступ'))
    op.add_column('users', sa.Column('dark_triads_full', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='тёмная триада'))
    op.add_column('users', sa.Column('love_access', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='романтические предпочтения доступ'))
    op.alter_column('users', 'gender',
               existing_type=postgresql.ENUM('male', 'girl', 'neutral', name='gender'),
               comment='gender',
               existing_comment='гендер',
               existing_nullable=False,
               existing_server_default=sa.text("'male'::gender"))
    op.drop_column('users', 'passed_sex_romance')
    op.drop_column('users', 'passed_body_image_eating')
    op.drop_column('users', 'passed_mood_anxiety')
    op.drop_column('users', 'passed_neurodiversity')
    op.drop_column('users', 'passed_holland')
    op.drop_column('users', 'passed_personality_core')
    op.alter_column('user_dark_triads', 'psychoticism',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Психотизм: 0=нормальность, эмпатия → 1=холодность, необычный опыт',
               existing_nullable=True)
    op.alter_column('user_dark_triads', 'machiavellianism',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Макиавеллизм: 0=прямой и честный → 1=манипулятивный, хитрый',
               existing_nullable=True)
    op.alter_column('user_dark_triads', 'narcissism',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Нарциссизм: 0=скромный → 1=самолюбование, грандиозность',
               existing_nullable=True)
    op.alter_column('user_dark_triads', 'cynicism',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='0=глубокая вера в доброту людей → 1=циничный, недоверие к мотивам людей',
               existing_nullable=True)
    # ### end Alembic commands ###
