"""empty message

Revision ID: 25e53c59ffb0
Revises: cdf0161e7777
Create Date: 2026-02-21 00:28:12.030533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25e53c59ffb0'
down_revision = 'cdf0161e7777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_diary_created_at'), table_name='user_diary')
    op.create_index(op.f('ix_user_diary_created_at'), 'user_diary', ['created_at'], unique=False)
    op.drop_column('user_holland_codes', 'notes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_holland_codes', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True, comment='Описание типа Холланда'))
    op.drop_index(op.f('ix_user_diary_created_at'), table_name='user_diary')
    op.create_index(op.f('ix_user_diary_created_at'), 'user_diary', ['created_at'], unique=True)
    # ### end Alembic commands ###
