"""empty message

Revision ID: 33295b103050
Revises: 
Create Date: 2026-02-13 14:48:50.006958

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '33295b103050'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('telegram_id', sa.String(), nullable=False, comment='tg id'),
    sa.Column('username', sa.String(), nullable=False, comment='username'),
    sa.Column('first_name', sa.String(), nullable=True, comment='first name'),
    sa.Column('last_name', sa.String(), nullable=True, comment='last name'),
    sa.Column('talk_mode', sa.Enum('research', 'psycho', name='talking_modes'), server_default='psycho', nullable=False, comment='режим общения'),
    sa.Column('used_voice_messages', sa.Integer(), server_default='0', nullable=False, comment='использовано голосовых сообщений'),
    sa.Column('full_access', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='полный доступ: безлимит гс, базовая характеристика'),
    sa.Column('dark_triads_full', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='тёмная триада'),
    sa.Column('humor_access', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='базовая характеристика доступ'),
    sa.Column('clinical_access', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='клиническая характеристика доступ'),
    sa.Column('love_access', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='романтические предпочтения доступ'),
    sa.Column('age', sa.Integer(), nullable=True, comment='возраст (предугадывает нейронка)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('anxiety_ocd_trauma_disorders',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='ID пользователя'),
    sa.Column('gad', sa.Float(), nullable=True, comment='Генерализованное тревожное расстройство (0-1)'),
    sa.Column('gad_worry', sa.Float(), nullable=True, comment='Беспокойство (0-1)'),
    sa.Column('gad_restlessness', sa.Float(), nullable=True, comment='Беспокойство/нервозность (0-1)'),
    sa.Column('gad_fatigue', sa.Float(), nullable=True, comment='Утомляемость (0-1)'),
    sa.Column('gad_concentration', sa.Float(), nullable=True, comment='Нарушения концентрации (0-1)'),
    sa.Column('gad_irritability', sa.Float(), nullable=True, comment='Раздражительность (0-1)'),
    sa.Column('gad_muscle', sa.Float(), nullable=True, comment='Мышечное напряжение (0-1)'),
    sa.Column('gad_sleep', sa.Float(), nullable=True, comment='Нарушения сна (0-1)'),
    sa.Column('panic', sa.Float(), nullable=True, comment='Паническое расстройство (0-1)'),
    sa.Column('panic_frequency', sa.String(length=20), nullable=True, comment='Частота панических атак'),
    sa.Column('panic_anticipatory', sa.Float(), nullable=True, comment='Тревога ожидания (0-1)'),
    sa.Column('social_anxiety', sa.Float(), nullable=True, comment='Социальная тревога (0-1)'),
    sa.Column('social_avoidance', sa.Float(), nullable=True, comment='Избегание социальных ситуаций (0-1)'),
    sa.Column('ocd', sa.Float(), nullable=True, comment='Обсессивно-компульсивное расстройство (0-1)'),
    sa.Column('ocd_obsessions', sa.Float(), nullable=True, comment='Навязчивые мысли (0-1)'),
    sa.Column('ocd_compulsions', sa.Float(), nullable=True, comment='Компульсивные действия (0-1)'),
    sa.Column('ocd_insight', sa.Float(), nullable=True, comment='Критичность к симптомам (0-1)'),
    sa.Column('body_dysmorphia', sa.Float(), nullable=True, comment='Дисморфофобия (0-1)'),
    sa.Column('bfrb', sa.Float(), nullable=True, comment='Повторяющееся поведение (0-1)'),
    sa.Column('ptsd', sa.Float(), nullable=True, comment='Посттравматическое стрессовое расстройство (0-1)'),
    sa.Column('ptsd_intrusions', sa.Float(), nullable=True, comment='Интрузивные воспоминания (0-1)'),
    sa.Column('ptsd_avoidance', sa.Float(), nullable=True, comment='Избегание триггеров (0-1)'),
    sa.Column('ptsd_cognition', sa.Float(), nullable=True, comment='Негативные мысли (0-1)'),
    sa.Column('ptsd_arousal', sa.Float(), nullable=True, comment='Гипервозбуждение (0-1)'),
    sa.Column('acute_stress', sa.Float(), nullable=True, comment='Острое стрессовое расстройство (0-1)'),
    sa.Column('cptsd', sa.Float(), nullable=True, comment='Комплексное ПТСР (0-1)'),
    sa.Column('cptsd_emotion', sa.Float(), nullable=True, comment='Нарушения эмоциональной регуляции (0-1)'),
    sa.Column('cptsd_self', sa.Float(), nullable=True, comment='Нарушения самооценки (0-1)'),
    sa.Column('cptsd_relations', sa.Float(), nullable=True, comment='Нарушения в отношениях (0-1)'),
    sa.Column('dissociative', sa.Float(), nullable=True, comment='Диссоциативные симптомы (0-1)'),
    sa.Column('amnesia', sa.Float(), nullable=True, comment='Амнезия (0-1)'),
    sa.Column('did', sa.Float(), nullable=True, comment='Диссоциативное расстройство идентичности (0-1)'),
    sa.Column('depersonalization', sa.Float(), nullable=True, comment='Деперсонализация/дереализация (0-1)'),
    sa.Column('records', sa.Integer(), nullable=True, comment='количество записей'),
    sa.Column('accuracy_percent', sa.Float(), nullable=True, comment='процент точности'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anxiety_ocd_trauma_disorders_user_id'), 'anxiety_ocd_trauma_disorders', ['user_id'], unique=False)
    op.create_table('characteristic_batch_logs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('characteristic_type', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_batch_user_type_created', 'characteristic_batch_logs', ['user_id', 'characteristic_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_characteristic_batch_logs_characteristic_type'), 'characteristic_batch_logs', ['characteristic_type'], unique=False)
    op.create_index(op.f('ix_characteristic_batch_logs_user_id'), 'characteristic_batch_logs', ['user_id'], unique=False)
    op.create_table('clinical_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='ID пользователя'),
    sa.Column('overall_severity', sa.String(length=20), nullable=True, comment='Общая тяжесть состояния'),
    sa.Column('diagnosis_status', sa.String(length=30), nullable=True, comment='Статус диагностики'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Заметки и комментарии исходя из других характеристик'),
    sa.Column('suicide_risk', sa.Float(), nullable=True, comment='Уровень суицидального риска (0-1)'),
    sa.Column('suicide_ideation_frequency', sa.String(length=20), nullable=True, comment='Частота суицидальных мыслей'),
    sa.Column('records', sa.Integer(), nullable=True, comment='количество записей'),
    sa.Column('accuracy_percent', sa.Float(), nullable=True, comment='процент точности'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cognitive_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reflectiveness', sa.Float(), nullable=True, comment='Саморефлексия.'),
    sa.Column('intuitiveness', sa.Float(), nullable=True, comment='Опора на интуицию'),
    sa.Column('fantasy_prone', sa.Float(), nullable=True, comment='0=приземленный/реалистичный, 1=склонный к фантазиям/мечтательный'),
    sa.Column('creativity', sa.Float(), nullable=True, comment='0=практичный, 1=креативный'),
    sa.Column('thinking_style', sa.Float(), nullable=True, comment='Деревья важнее леса? 0=простой тип мышления, 1=аналитический/многомерный/сложный тип мышления'),
    sa.Column('tolerance_for_ambiguity', sa.Float(), nullable=True, comment='0=любит ясность и правила, 1=комфортно с неопределенностью'),
    sa.Column('mental_flexibility', sa.Float(), nullable=True, comment='Адаптивность. 0=ригидный, 1=гибкий'),
    sa.Column('records', sa.Integer(), nullable=True, comment='количество записей'),
    sa.Column('accuracy_percent', sa.Float(), nullable=True, comment='процент точности'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emotional_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('optimism', sa.Float(), nullable=True, comment='0=пессимист, 1=оптимист'),
    sa.Column('self_esteem', sa.Float(), nullable=True, comment='Самооценка. 0=низкая самооценка, 1=высокая самооценка'),
    sa.Column('self_irony', sa.Float(), nullable=True, comment='Способность к самоиронии'),
    sa.Column('intimacy_capacity', sa.Float(), nullable=True, comment='Способность к глубокой эмоциональной близости.'),
    sa.Column('emotional_sensitivity', sa.Float(), nullable=True, comment='Внутренняя эмоциональная чувствительность.'),
    sa.Column('emotional_expressiveness', sa.Float(), nullable=True, comment='Внешняя эмоциональность. 0=сдержанный в эмоциях, 1=эмоционально открытый.'),
    sa.Column('anxiety_level', sa.Float(), nullable=True, comment='Тревожность.'),
    sa.Column('records', sa.Integer(), nullable=True, comment='количество записей'),
    sa.Column('accuracy_percent', sa.Float(), nullable=True, comment='процент точности'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mood_disorders',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='ID пользователя'),
    sa.Column('depression', sa.Float(), nullable=True, comment='Уровень депрессии (0-1)'),
    sa.Column('depression_sadness', sa.Float(), nullable=True, comment='Грусть (0-1)'),
    sa.Column('depression_anhedonia', sa.Float(), nullable=True, comment='Ангедония (0-1)'),
    sa.Column('depression_appetite', sa.Float(), nullable=True, comment='Нарушение аппетита (0-1)'),
    sa.Column('depression_sleep', sa.Float(), nullable=True, comment='Нарушения сна (0-1)'),
    sa.Column('depression_fatigue', sa.Float(), nullable=True, comment='Усталость (0-1)'),
    sa.Column('depression_worthlessness', sa.Float(), nullable=True, comment='Чувство никчемности (0-1)'),
    sa.Column('depression_concentration', sa.Float(), nullable=True, comment='Нарушения концентрации (0-1)'),
    sa.Column('depression_suicidal', sa.Float(), nullable=True, comment='Суицидальные мысли (0-1)'),
    sa.Column('bipolar', sa.Float(), nullable=True, comment='Биполярное расстройство (0-1)'),
    sa.Column('bipolar_mania', sa.Float(), nullable=True, comment='Маниакальные эпизоды (0-1)'),
    sa.Column('bipolar_hypomania', sa.Float(), nullable=True, comment='Гипоманиакальные эпизоды (0-1)'),
    sa.Column('bipolar_depression', sa.Float(), nullable=True, comment='Депрессивные эпизоды (0-1)'),
    sa.Column('bipolar_rapid', sa.Float(), nullable=True, comment='Быстрая смена фаз (0-1)'),
    sa.Column('bipolar_psychotic', sa.Float(), nullable=True, comment='Психотические черты (0-1)'),
    sa.Column('cyclothymia', sa.Float(), nullable=True, comment='Циклотимия (0-1)'),
    sa.Column('records', sa.Integer(), nullable=True, comment='количество записей'),
    sa.Column('accuracy_percent', sa.Float(), nullable=True, comment='процент точности'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('neuro_disorders',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='ID пользователя'),
    sa.Column('adhd', sa.Float(), nullable=True, comment='вероятность СДВГ (0-1)'),
    sa.Column('adhd_inattention', sa.Float(), nullable=True, comment='Невнимательность (0-1)'),
    sa.Column('adhd_hyperactivity', sa.Float(), nullable=True, comment='Гиперактивность (0-1)'),
    sa.Column('adhd_impulsivity', sa.Float(), nullable=True, comment='Импульсивность (0-1)'),
    sa.Column('autism', sa.Float(), nullable=True, comment='Аутистические черты (0-1)'),
    sa.Column('autism_social', sa.Float(), nullable=True, comment='Нарушения социальной коммуникации (0-1)'),
    sa.Column('autism_interests', sa.Float(), nullable=True, comment='Ограниченные интересы/ритуалы (0-1)'),
    sa.Column('eating', sa.Float(), nullable=True, comment='Общий уровень РПП (0-1)'),
    sa.Column('anorexia', sa.Float(), nullable=True, comment='Нервная анорексия (0-1)'),
    sa.Column('bulimia', sa.Float(), nullable=True, comment='Нервная булимия (0-1)'),
    sa.Column('binge', sa.Float(), nullable=True, comment='Компульсивное переедание (0-1)'),
    sa.Column('records', sa.Integer(), nullable=True, comment='количество записей'),
    sa.Column('accuracy_percent', sa.Float(), nullable=True, comment='процент точности'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personality_disorders',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='ID пользователя'),
    sa.Column('bpd_severity', sa.Float(), nullable=True, comment='Тяжесть ПРЛ (0-1)'),
    sa.Column('bpd_abandonment', sa.Float(), nullable=True, comment='Страх брошенности (0-1)'),
    sa.Column('bpd_unstable_relations', sa.Float(), nullable=True, comment='Нестабильные отношения (0-1)'),
    sa.Column('bpd_identity', sa.Float(), nullable=True, comment='Нарушение идентичности (0-1)'),
    sa.Column('bpd_impulsivity', sa.Float(), nullable=True, comment='Импульсивность (0-1)'),
    sa.Column('bpd_suicidal', sa.Float(), nullable=True, comment='Суицидальное поведение (0-1)'),
    sa.Column('bpd_mood_swings', sa.Float(), nullable=True, comment='Перепады настроения (0-1)'),
    sa.Column('bpd_emptiness', sa.Float(), nullable=True, comment='Чувство пустоты (0-1)'),
    sa.Column('bpd_anger', sa.Float(), nullable=True, comment='Неадекватный гнев (0-1)'),
    sa.Column('bpd_paranoia', sa.Float(), nullable=True, comment='Параноидные идеи (0-1)'),
    sa.Column('npd', sa.Float(), nullable=True, comment='Нарциссическое РЛ (0-1)'),
    sa.Column('aspd', sa.Float(), nullable=True, comment='Антисоциальное РЛ (0-1)'),
    sa.Column('avpd', sa.Float(), nullable=True, comment='Избегающее РЛ (0-1)'),
    sa.Column('dpd', sa.Float(), nullable=True, comment='Зависимое РЛ (0-1)'),
    sa.Column('ocpd', sa.Float(), nullable=True, comment='Обсессивно-компульсивное РЛ (0-1)'),
    sa.Column('ppd', sa.Float(), nullable=True, comment='Параноидное РЛ (0-1)'),
    sa.Column('szpd', sa.Float(), nullable=True, comment='Шизоидное РЛ (0-1)'),
    sa.Column('stpd', sa.Float(), nullable=True, comment='Шизотипическое РЛ (0-1)'),
    sa.Column('records', sa.Integer(), nullable=True, comment='количество записей'),
    sa.Column('accuracy_percent', sa.Float(), nullable=True, comment='процент точности'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('locus_control', sa.Float(), nullable=True, comment='0=другие люди виноваты в моих проблемах, 1=сам отвечаю за свою жизнь'),
    sa.Column('independence', sa.Float(), nullable=True, comment='0=зависим от мнения людей, 1=независим от мнения людей'),
    sa.Column('empathy', sa.Float(), nullable=True, comment='Способность понимать чувства других.'),
    sa.Column('physical_sensitivity', sa.Float(), nullable=True, comment='Тактильность'),
    sa.Column('extraversion', sa.Float(), nullable=True, comment='0=интроверт, 1=экстраверт'),
    sa.Column('altruism', sa.Float(), nullable=True, comment='эгоизм → бескорыстная помощь'),
    sa.Column('conformity', sa.Float(), nullable=True, comment='Конформизм'),
    sa.Column('social_confidence', sa.Float(), nullable=True, comment='0=застенчивый, 1=уверенный в общении'),
    sa.Column('competitiveness', sa.Float(), nullable=True, comment='0=кооперативный, 1=соревновательный'),
    sa.Column('records', sa.Integer(), nullable=True, comment='количество записей'),
    sa.Column('accuracy_percent', sa.Float(), nullable=True, comment='процент точности'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_behavioral_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('patience', sa.Float(), nullable=True, comment='Терпение во время стресса. 0=нетерпеливый, 1=терпеливый'),
    sa.Column('stress_tolerance', sa.Float(), nullable=True, comment='Насколько комфортно в стрессе'),
    sa.Column('ambition', sa.Float(), nullable=True, comment='Амбициозность. 0=нет целей, 1=амбициозный'),
    sa.Column('decisiveness', sa.Float(), nullable=True, comment='Решимость. 0=нерешительный, 1=решительный'),
    sa.Column('risk_taking', sa.Float(), nullable=True, comment='Рискованность. 0=осторожный, 1=рискующий'),
    sa.Column('perfectionism', sa.Float(), nullable=True, comment='Требования к порядку. 0=непритязательный, 1=перфекционист'),
    sa.Column('impulse_control', sa.Float(), nullable=True, comment='Самоконтроль. 0=импульсивный, 1=сдержанный'),
    sa.Column('records', sa.Integer(), nullable=True, comment='количество записей'),
    sa.Column('accuracy_percent', sa.Float(), nullable=True, comment='процент точности'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_dark_triads',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cynicism', sa.Float(), nullable=True),
    sa.Column('narcissism', sa.Float(), nullable=True),
    sa.Column('machiavellianism', sa.Float(), nullable=True),
    sa.Column('psychoticism', sa.Float(), nullable=True),
    sa.Column('records', sa.Integer(), nullable=True, comment='количество записей'),
    sa.Column('accuracy_percent', sa.Float(), nullable=True, comment='процент точности'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_diary',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_diary_user_id'), 'user_diary', ['user_id'], unique=False)
    op.create_table('user_hexaco',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('honesty_humility', sa.Float(), nullable=True, comment='H: 0=манипулятивный, нарциссичный, жадный → 1=искренний, скромный, бескорыстный'),
    sa.Column('emotionality', sa.Float(), nullable=True, comment='E: эмоциональность, тревожность, сентиментальность'),
    sa.Column('extraversion', sa.Float(), nullable=True, comment='X: экстраверсия, социальность'),
    sa.Column('agreeableness', sa.Float(), nullable=True, comment='A: согласность, терпимость, мягкость'),
    sa.Column('conscientiousness', sa.Float(), nullable=True, comment='C: добросовестность, организованность'),
    sa.Column('openness', sa.Float(), nullable=True, comment='O: открытость опыту, креативность'),
    sa.Column('records', sa.Integer(), nullable=True, comment='количество записей'),
    sa.Column('accuracy_percent', sa.Float(), nullable=True, comment='процент точности'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_holland_codes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('realistic', sa.Float(), nullable=True, comment='R — Реалистичный: работа руками, техника, природа, спорт'),
    sa.Column('investigative', sa.Float(), nullable=True, comment='I — Исследовательский: наука, анализ, решение сложных задач'),
    sa.Column('artistic', sa.Float(), nullable=True, comment='A — Артистичный: творчество, самовыражение, искусство'),
    sa.Column('social', sa.Float(), nullable=True, comment='S — Социальный: помощь людям, общение, обучение'),
    sa.Column('enterprising', sa.Float(), nullable=True, comment='E — Предприимчивый: лидерство, продажи, убеждение'),
    sa.Column('conventional', sa.Float(), nullable=True, comment='C — Конвенциональный: порядок, правила, структура, финансы'),
    sa.Column('holland_code', sa.String(length=6), nullable=True, comment="Топ-3 типа, например 'RIA' или 'SEC'"),
    sa.Column('confidence_level', sa.Float(), nullable=True, comment='Уверенность в точности определения типа (0.0 — совсем не уверен, 1.0 — абсолютно уверен)'),
    sa.Column('differentiation_index', sa.Float(), nullable=True, comment='Индекс дифференциации профиля (чем выше, тем более выражены различия между типами)'),
    sa.Column('consistency_index', sa.Float(), nullable=True, comment='Индекс согласованности типов (чем выше, тем более согласован профиль)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Описание типа Холланда'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_humor_sense',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('affiliative_humor', sa.Float(), nullable=True, comment='Аффилиативный юмор: для укрепления социальных связей, дружеский, групповой (0=редко, 1=часто использует)'),
    sa.Column('puns_wordplay', sa.Float(), nullable=True, comment='Игры слов, каламбуры, панчи (0=не ценит, 1=обожает)'),
    sa.Column('slapstick_physical', sa.Float(), nullable=True, comment='Физический юмор: падения, клоунада, визуальные гэги (0=не смешно, 1=веселит)'),
    sa.Column('observational_humor', sa.Float(), nullable=True, comment='Наблюдательный юмор: о повседневной жизни, стереотипах (0=редко, 1=часто замечает)'),
    sa.Column('self_enhancing_humor', sa.Float(), nullable=True, comment='Самоподдерживающий юмор: для coping со стрессом, позитивный взгляд на жизнь (0=редко, 1=часто)'),
    sa.Column('humor_frequency', sa.Float(), nullable=True, comment='Частота использования юмора в общении (0=редко шутит, 1=постоянно)'),
    sa.Column('humor_in_stress', sa.Float(), nullable=True, comment='Юмор в стрессовых ситуациях: как coping-механизм (0=становится серьезным, 1=шутит чтобы разрядить)'),
    sa.Column('humor_in_social', sa.Float(), nullable=True, comment='Юмор в социальных взаимодействиях: для ice-breaking (0=стесняется, 1=активно использует)'),
    sa.Column('aggressive_humor', sa.Float(), nullable=True, comment='Агрессивный юмор: сарказм, насмешка над другими, критика (0=избегает, 1=любит)'),
    sa.Column('sarcasm_level', sa.Float(), nullable=True, comment='Сарказм: ирония, подколы (0=не любит, 1=мастер сарказма)'),
    sa.Column('satirical_parody', sa.Float(), nullable=True, comment='Сатира, пародия: критика общества, имитация (0=не интересует, 1=ценит)'),
    sa.Column('dark_humor', sa.Float(), nullable=True, comment='Черный юмор: о смерти, трагедиях, taboo-темах (0=отталкивает, 1=привлекает)'),
    sa.Column('self_defeating_humor', sa.Float(), nullable=True, comment='Самоуничижительный юмор: самоирония, юмор за свой счет для принятия (0=избегает, 1=часто)'),
    sa.Column('self_deprecating', sa.Float(), nullable=True, comment='Самоирония: шутки над собой (0=избегает, 1=часто использует)'),
    sa.Column('witty_quick', sa.Float(), nullable=True, comment='Остроумный юмор: быстрые реплики, интеллект (0=медленный, 1=острый ум)'),
    sa.Column('absurd_surreal', sa.Float(), nullable=True, comment='Абсурдный юмор: нелогичный, сюрреалистичный (0=не понимает, 1=любит)'),
    sa.Column('dry_deadpan', sa.Float(), nullable=True, comment='Сухой юмор: deadpan, без эмоций (0=не замечает, 1=мастер)'),
    sa.Column('records', sa.Integer(), nullable=True, comment='количество записей'),
    sa.Column('accuracy_percent', sa.Float(), nullable=True, comment='процент точности'),
    sa.Column('dominant_humor', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_logs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('log', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_userlog_date', 'user_logs', ['created_at'], unique=False)
    op.create_index('idx_userlog_user_created_at', 'user_logs', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_userlog_user_date', 'user_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_user_logs_user_id'), 'user_logs', ['user_id'], unique=False)
    op.create_table('user_socionics',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('socionics_type', sa.Enum('ИЛЭ', 'СЭИ', 'ЭСЭ', 'ЛИИ', 'СЛЭ', 'ИЭИ', 'ЭИЭ', 'ЛСИ', 'СЭЭ', 'ИЛИ', 'ЛИЭ', 'ЭСИ', 'ЛСЭ', 'ЭИИ', 'ИЭЭ', 'СЛИ', name='socionics_type'), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_comparison',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный идентификатор сравнения'),
    sa.Column('user_a_id', sa.UUID(), nullable=False, comment='ID первого пользователя'),
    sa.Column('user_b_id', sa.UUID(), nullable=False, comment='ID второго пользователя'),
    sa.Column('holland_code', sa.Text(), nullable=True, comment='Совместимость по кодам Голланда'),
    sa.Column('hecaxo', sa.Text(), nullable=True, comment='Совместимость по HECAxo'),
    sa.Column('socionics', sa.Text(), nullable=True, comment='Совместимость по соционике'),
    sa.Column('basic_traits', sa.Text(), nullable=True, comment='Совместимость по базовым чертам'),
    sa.Column('clinic_traits', sa.Text(), nullable=True, comment='Совместимость по клиническим чертам'),
    sa.Column('summary', sa.Text(), nullable=True, comment='сводка совместимости'),
    sa.Column('compatibility_score', sa.Float(), nullable=True, comment='Общая оценка совместимости (0-100)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_a_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_b_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_comparison_user_a_id'), 'users_comparison', ['user_a_id'], unique=False)
    op.create_index(op.f('ix_users_comparison_user_b_id'), 'users_comparison', ['user_b_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_comparison_user_b_id'), table_name='users_comparison')
    op.drop_index(op.f('ix_users_comparison_user_a_id'), table_name='users_comparison')
    op.drop_table('users_comparison')
    op.drop_table('user_socionics')
    op.drop_index(op.f('ix_user_logs_user_id'), table_name='user_logs')
    op.drop_index('idx_userlog_user_date', table_name='user_logs')
    op.drop_index('idx_userlog_user_created_at', table_name='user_logs')
    op.drop_index('idx_userlog_date', table_name='user_logs')
    op.drop_table('user_logs')
    op.drop_table('user_humor_sense')
    op.drop_table('user_holland_codes')
    op.drop_table('user_hexaco')
    op.drop_index(op.f('ix_user_diary_user_id'), table_name='user_diary')
    op.drop_table('user_diary')
    op.drop_table('user_dark_triads')
    op.drop_table('user_behavioral_profiles')
    op.drop_table('social_profiles')
    op.drop_table('personality_disorders')
    op.drop_table('neuro_disorders')
    op.drop_table('mood_disorders')
    op.drop_table('emotional_profiles')
    op.drop_table('cognitive_profiles')
    op.drop_table('clinical_profiles')
    op.drop_index(op.f('ix_characteristic_batch_logs_user_id'), table_name='characteristic_batch_logs')
    op.drop_index(op.f('ix_characteristic_batch_logs_characteristic_type'), table_name='characteristic_batch_logs')
    op.drop_index('ix_batch_user_type_created', table_name='characteristic_batch_logs')
    op.drop_table('characteristic_batch_logs')
    op.drop_index(op.f('ix_anxiety_ocd_trauma_disorders_user_id'), table_name='anxiety_ocd_trauma_disorders')
    op.drop_table('anxiety_ocd_trauma_disorders')
    op.drop_table('users')
    # ### end Alembic commands ###
