"""empty message

Revision ID: 352ed5d627f2
Revises: 3cacedd59277
Create Date: 2026-02-15 11:30:20.261338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '352ed5d627f2'
down_revision = '3cacedd59277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_diary_created_at'), table_name='user_diary')
    op.create_index(op.f('ix_user_diary_created_at'), 'user_diary', ['created_at'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_diary_created_at'), table_name='user_diary')
    op.create_index(op.f('ix_user_diary_created_at'), 'user_diary', ['created_at'], unique=False)
    # ### end Alembic commands ###
