"""empty message

Revision ID: 432603828ec0
Revises: ce05aa31192f
Create Date: 2026-02-18 17:56:41.114955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '432603828ec0'
down_revision = 'ce05aa31192f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_diary', sa.Column('context_text', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_diary', 'context_text')
    # ### end Alembic commands ###
