"""empty message

Revision ID: 46aac306e58b
Revises: 8d194a76f516
Create Date: 2026-03-19 14:04:24.183237

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '46aac306e58b'
down_revision = '8d194a76f516'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adhd_disorder',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='ID пользователя'),
    sa.Column('adhd', sa.Float(), nullable=True, comment='уровень СДВГ (0-1)'),
    sa.Column('adhd_inattention', sa.Float(), nullable=True, comment='Невнимательность (0-1)'),
    sa.Column('adhd_hyperactivity', sa.Float(), nullable=True, comment='Гиперактивность (0-1)'),
    sa.Column('hyperfocus', sa.Float(), nullable=True, comment='Склонность к гиперфокусу (осознанная защитная реакция) (0-1)'),
    sa.Column('internal_hyperactivity', sa.Float(), nullable=True, comment='Внутренняя гиперактивность / постоянный внутренний шум (0-1)'),
    sa.Column('time_blindness', sa.Float(), nullable=True, comment='Нарушение чувства времени / тайм-слепота (0-1)'),
    sa.Column('motivation_problems', sa.Float(), nullable=True, comment="Проблемы с внутренней мотивацией / прокрастинация при отсутствии дофаминового 'пинка' (0-1)"),
    sa.Column('accuracy_percent', sa.Float(), nullable=True, comment='процент точности'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('autism_disorder',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('autism', sa.Float(), nullable=True, comment='Аутистические черты (0-1)'),
    sa.Column('autism_social', sa.Float(), nullable=True, comment='Нарушения социальной коммуникации (0-1)'),
    sa.Column('autism_interests', sa.Float(), nullable=True, comment='Ограниченные интересы/ритуалы (0-1)'),
    sa.Column('masking', sa.Float(), nullable=True, comment='Маскировка / подавление аутистических черт для адаптации (0-1)'),
    sa.Column('sensory_overload', sa.Float(), nullable=True, comment='Сенсорная перегрузка / гиперчувствительность к стимулам (0-1)'),
    sa.Column('accuracy_percent', sa.Float(), nullable=True, comment='процент точности'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autism_disorder_user_id'), 'autism_disorder', ['user_id'], unique=False)
    op.create_table('bipolar_disorder',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bipolar_score', sa.Float(), nullable=True, comment='Вероятность биполярного расстройства (0-1)'),
    sa.Column('bipolar_mania', sa.Float(), nullable=True, comment='Маниакальные эпизоды (0-1)'),
    sa.Column('bipolar_hypomania', sa.Float(), nullable=True, comment='Гипоманиакальные эпизоды (0-1)'),
    sa.Column('bipolar_depression', sa.Float(), nullable=True, comment='Депрессивные эпизоды (0-1)'),
    sa.Column('bipolar_rapid', sa.Float(), nullable=True, comment='Частота смены фаз (0-1)'),
    sa.Column('bipolar_psychotic', sa.Float(), nullable=True, comment='Психотические черты (0-1)'),
    sa.Column('accuracy_percent', sa.Float(), nullable=True, comment='процент точности'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bipolar_disorder_user_id'), 'bipolar_disorder', ['user_id'], unique=False)
    op.create_table('bpd_disorder',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='ID пользователя'),
    sa.Column('bpd_severity', sa.Float(), nullable=True, comment='Уровень ПРЛ (0-1)'),
    sa.Column('bpd_abandonment', sa.Float(), nullable=True, comment='Страх брошенности (0-1)'),
    sa.Column('bpd_unstable_relations', sa.Float(), nullable=True, comment='Нестабильные отношения (0-1)'),
    sa.Column('bpd_identity', sa.Float(), nullable=True, comment='Нарушение идентичности (0-1)'),
    sa.Column('bpd_impulsivity', sa.Float(), nullable=True, comment='Импульсивность (0-1)'),
    sa.Column('bpd_mood_swings', sa.Float(), nullable=True, comment='Перепады настроения (0-1)'),
    sa.Column('bpd_emptiness', sa.Float(), nullable=True, comment='Чувство пустоты (0-1)'),
    sa.Column('bpd_anger', sa.Float(), nullable=True, comment='Неадекватный гнев (0-1)'),
    sa.Column('bpd_paranoia', sa.Float(), nullable=True, comment='Параноидные идеи (0-1)'),
    sa.Column('bpd_suicidal', sa.Float(), nullable=True, comment='Суицидальное поведение, угрозы, самоповреждения (0-1)'),
    sa.Column('accuracy_percent', sa.Float(), nullable=True, comment='процент точности'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('depression_disorder',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('depression_score', sa.Float(), nullable=True, comment='Уровень депрессии (0-1)'),
    sa.Column('anhedonia', sa.Float(), nullable=True, comment='Ангедония / потеря интереса и удовольствия (0-1)'),
    sa.Column('fatigue', sa.Float(), nullable=True, comment='Усталость, потеря энергии, ощущение истощения (0-1)'),
    sa.Column('sleep_disturbance', sa.Float(), nullable=True, comment='Нарушения сна (бессонница / гиперсомния) (0-1)'),
    sa.Column('worthlessness', sa.Float(), nullable=True, comment='Чувство никчёмности, вины (0-1)'),
    sa.Column('suicidal', sa.Float(), nullable=True, comment='Суицидальные мысли / поведение (0-1)'),
    sa.Column('accuracy_percent', sa.Float(), nullable=True, comment='процент точности'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_depression_disorder_user_id'), 'depression_disorder', ['user_id'], unique=False)
    op.create_table('dissociative_disorder',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dissociative', sa.Float(), nullable=True, comment='Диссоциативные симптомы (0-1)'),
    sa.Column('depersonalization', sa.Float(), nullable=True, comment='Деперсонализация / дереализация (0-1)'),
    sa.Column('amnesia', sa.Float(), nullable=True, comment='Амнезия (0-1)'),
    sa.Column('did', sa.Float(), nullable=True, comment='Диссоциативное расстройство идентичности / раздвоение личности (0-1)'),
    sa.Column('accuracy_percent', sa.Float(), nullable=True, comment='процент точности'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dissociative_disorder_user_id'), 'dissociative_disorder', ['user_id'], unique=False)
    op.create_table('eating_disorder',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('eating', sa.Float(), nullable=True, comment='Общий уровень РПП (0-1)'),
    sa.Column('anorexia', sa.Float(), nullable=True, comment='Нарушение аппетита / анорексия (0-1)'),
    sa.Column('bulimia', sa.Float(), nullable=True, comment='Слишком сильный аппетит / булимия (0-1)'),
    sa.Column('binge', sa.Float(), nullable=True, comment='Компульсивное переедание (0-1)'),
    sa.Column('body_image_distress', sa.Float(), nullable=True, comment='Дистресс от образа тела / недовольство внешностью (0-1)'),
    sa.Column('compensatory_behaviors', sa.Float(), nullable=True, comment='Компенсаторное поведение (рвота, слабительные, чрезмерные тренировки) (0-1)'),
    sa.Column('accuracy_percent', sa.Float(), nullable=True, comment='процент точности'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eating_disorder_user_id'), 'eating_disorder', ['user_id'], unique=False)
    op.create_table('gdr_disorder',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('gad_worry', sa.Float(), nullable=True, comment='Чрезмерное беспокойство / тревожные ожидания (0-1)'),
    sa.Column('gad_uncontrollable', sa.Float(), nullable=True, comment='Трудности с контролем беспокойства (0-1)'),
    sa.Column('gad_catastrophic', sa.Float(), nullable=True, comment='Предчувствие беды / ощущение надвигающейся катастрофы (0-1)'),
    sa.Column('gad_restlessness', sa.Float(), nullable=True, comment='Моторное беспокойство, неусидчивость, ощущение на взводе (0-1)'),
    sa.Column('gad_fatigue', sa.Float(), nullable=True, comment='Лёгкая утомляемость, быстрое истощение (0-1)'),
    sa.Column('gad_concentration', sa.Float(), nullable=True, comment='Трудности с концентрацией внимания, «пустота в голове» (0-1)'),
    sa.Column('gad_irritability', sa.Float(), nullable=True, comment='Раздражительность, вспыльчивость (0-1)'),
    sa.Column('gad_muscle_tension', sa.Float(), nullable=True, comment='Мышечное напряжение, скованность (0-1)'),
    sa.Column('gad_relaxation', sa.Float(), nullable=True, comment='Трудности с расслаблением (0-1)'),
    sa.Column('accuracy_percent', sa.Float(), nullable=True, comment='процент точности'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gdr_disorder_user_id'), 'gdr_disorder', ['user_id'], unique=False)
    op.create_table('looks_disorder',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bdd_general', sa.Float(), nullable=True, comment='Общий уровень дисморфофобии (0-1)'),
    sa.Column('muscle_dysmorphia', sa.Float(), nullable=True, comment='Мышечная дисморфия / bigorexia (0-1)'),
    sa.Column('skin_hair_focus', sa.Float(), nullable=True, comment='Кожа, акне (0-1)'),
    sa.Column('hair_focus', sa.Float(), nullable=True, comment='Облысение / растительность на лице (0-1)'),
    sa.Column('facial_features', sa.Float(), nullable=True, comment='Черты лица (нос, губы, глаза, симметрия, луксмаксинг) (0-1)'),
    sa.Column('body_fat', sa.Float(), nullable=True, comment='Жир, целлюлит, вес (0-1)'),
    sa.Column('genitals_size', sa.Float(), nullable=True, comment='Размер / форма гениталий (0-1)'),
    sa.Column('height_stature', sa.Float(), nullable=True, comment='Рост, пропорции тела, осанка (0-1)'),
    sa.Column('aging', sa.Float(), nullable=True, comment='Старение (0-1)'),
    sa.Column('reassurance', sa.Float(), nullable=True, comment='Частота поиска подтверждения / вопросов о внешности (0-1)'),
    sa.Column('impairment', sa.Float(), nullable=True, comment='Нарушение жизни / избегание из-за озабоченности внешностью (0-1)'),
    sa.Column('accuracy_percent', sa.Float(), nullable=True, comment='процент точности'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('panic_disorder',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('attack_frequency', sa.Float(), nullable=True, comment='Частота полноценных панических атак (0-1)'),
    sa.Column('situational_avoid', sa.Float(), nullable=True, comment='Избегание ситуаций / мест (0-1)'),
    sa.Column('anticipatory', sa.Float(), nullable=True, comment='Тревога ожидания новой атаки (0-1)'),
    sa.Column('fear_catastrophe', sa.Float(), nullable=True, comment='Страх смерти / сумасшествия / потери контроля (0-1)'),
    sa.Column('life_impairment', sa.Float(), nullable=True, comment='Нарушение жизни / социальности / функционирования из-за панического расстройства (0-1)'),
    sa.Column('accuracy_percent', sa.Float(), nullable=True, comment='процент точности'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_panic_disorder_user_id'), 'panic_disorder', ['user_id'], unique=False)
    op.create_table('ptsd_disorder',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ptsd', sa.Float(), nullable=True, comment='Общий уровень ПТСР / комплексного ПТСР (0-1)'),
    sa.Column('ptsd_intrusions', sa.Float(), nullable=True, comment='Интрузивные воспоминания, флэшбэки (0-1)'),
    sa.Column('ptsd_cognition', sa.Float(), nullable=True, comment='Негативные изменения в мышлении и настроении (0-1)'),
    sa.Column('ptsd_arousal', sa.Float(), nullable=True, comment='Гипервозбуждение при триггере (0-1)'),
    sa.Column('ptsd_self', sa.Float(), nullable=True, comment='Нарушения самооценки, чувство никчёмности (0-1)'),
    sa.Column('ptsd_avoidance', sa.Float(), nullable=True, comment='Избегание триггеров, мыслей, мест (0-1)'),
    sa.Column('ptsd_relations', sa.Float(), nullable=True, comment='Нарушения в отношениях, недоверие (0-1)'),
    sa.Column('accuracy_percent', sa.Float(), nullable=True, comment='процент точности'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ptsd_disorder_user_id'), 'ptsd_disorder', ['user_id'], unique=False)
    op.drop_table('mood_disorders')
    op.drop_table('personality_disorders')
    op.drop_index(op.f('ix_anxiety_ocd_trauma_disorders_user_id'), table_name='anxiety_ocd_trauma_disorders')
    op.drop_table('anxiety_ocd_trauma_disorders')
    op.drop_table('clinical_profiles')
    op.drop_table('neuro_disorders')
    op.add_column('social_profiles', sa.Column('social_anxiety', sa.Float(), nullable=True, comment='Социальная тревога (0-1)'))
    op.add_column('social_profiles', sa.Column('social_avoidance', sa.Float(), nullable=True, comment='Избегание социальных ситуаций (0-1)'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_profiles', 'social_avoidance')
    op.drop_column('social_profiles', 'social_anxiety')
    op.create_table('neuro_disorders',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False, comment='ID пользователя'),
    sa.Column('adhd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='вероятность СДВГ (0-1)'),
    sa.Column('adhd_inattention', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Невнимательность (0-1)'),
    sa.Column('adhd_hyperactivity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Гиперактивность (0-1)'),
    sa.Column('adhd_impulsivity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Импульсивность (0-1)'),
    sa.Column('autism', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Аутистические черты (0-1)'),
    sa.Column('autism_social', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Нарушения социальной коммуникации (0-1)'),
    sa.Column('autism_interests', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Ограниченные интересы/ритуалы (0-1)'),
    sa.Column('eating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Общий уровень РПП (0-1)'),
    sa.Column('anorexia', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Нервная анорексия (0-1)'),
    sa.Column('bulimia', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Нервная булимия (0-1)'),
    sa.Column('binge', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Компульсивное переедание (0-1)'),
    sa.Column('accuracy_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='процент точности'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('neuro_disorders_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('neuro_disorders_pkey'))
    )
    op.create_table('clinical_profiles',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False, comment='ID пользователя'),
    sa.Column('overall_severity', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='Общая тяжесть состояния'),
    sa.Column('diagnosis_status', sa.VARCHAR(length=30), autoincrement=False, nullable=True, comment='Статус диагностики'),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True, comment='Заметки и комментарии исходя из других характеристик'),
    sa.Column('suicide_risk', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Уровень суицидального риска (0-1)'),
    sa.Column('suicide_ideation_frequency', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='Частота суицидальных мыслей'),
    sa.Column('accuracy_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='процент точности'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('clinical_profiles_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('clinical_profiles_pkey'))
    )
    op.create_table('anxiety_ocd_trauma_disorders',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False, comment='ID пользователя'),
    sa.Column('gad', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Генерализованное тревожное расстройство (0-1)'),
    sa.Column('gad_worry', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Беспокойство (0-1)'),
    sa.Column('gad_restlessness', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Беспокойство/нервозность (0-1)'),
    sa.Column('gad_fatigue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Утомляемость (0-1)'),
    sa.Column('gad_concentration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Нарушения концентрации (0-1)'),
    sa.Column('gad_irritability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Раздражительность (0-1)'),
    sa.Column('gad_muscle', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Мышечное напряжение (0-1)'),
    sa.Column('gad_sleep', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Нарушения сна (0-1)'),
    sa.Column('panic', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Паническое расстройство (0-1)'),
    sa.Column('panic_frequency', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Частота панических атак'),
    sa.Column('panic_anticipatory', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Тревога ожидания (0-1)'),
    sa.Column('social_anxiety', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Социальная тревога (0-1)'),
    sa.Column('social_avoidance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Избегание социальных ситуаций (0-1)'),
    sa.Column('ocd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Обсессивно-компульсивное расстройство (0-1)'),
    sa.Column('ocd_obsessions', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Навязчивые мысли (0-1)'),
    sa.Column('ocd_compulsions', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Компульсивные действия (0-1)'),
    sa.Column('ocd_insight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Критичность к симптомам (0-1)'),
    sa.Column('body_dysmorphia', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Дисморфофобия (0-1)'),
    sa.Column('bfrb', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Повторяющееся поведение (0-1)'),
    sa.Column('ptsd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Посттравматическое стрессовое расстройство (0-1)'),
    sa.Column('ptsd_intrusions', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Интрузивные воспоминания (0-1)'),
    sa.Column('ptsd_avoidance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Избегание триггеров (0-1)'),
    sa.Column('ptsd_cognition', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Негативные мысли (0-1)'),
    sa.Column('ptsd_arousal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Гипервозбуждение (0-1)'),
    sa.Column('acute_stress', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Острое стрессовое расстройство (0-1)'),
    sa.Column('cptsd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Комплексное ПТСР (0-1)'),
    sa.Column('cptsd_emotion', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Нарушения эмоциональной регуляции (0-1)'),
    sa.Column('cptsd_self', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Нарушения самооценки (0-1)'),
    sa.Column('cptsd_relations', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Нарушения в отношениях (0-1)'),
    sa.Column('dissociative', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Диссоциативные симптомы (0-1)'),
    sa.Column('amnesia', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Амнезия (0-1)'),
    sa.Column('did', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Диссоциативное расстройство идентичности (0-1)'),
    sa.Column('depersonalization', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Деперсонализация/дереализация (0-1)'),
    sa.Column('accuracy_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='процент точности'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('anxiety_ocd_trauma_disorders_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('anxiety_ocd_trauma_disorders_pkey'))
    )
    op.create_index(op.f('ix_anxiety_ocd_trauma_disorders_user_id'), 'anxiety_ocd_trauma_disorders', ['user_id'], unique=False)
    op.create_table('personality_disorders',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False, comment='ID пользователя'),
    sa.Column('bpd_severity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Тяжесть ПРЛ (0-1)'),
    sa.Column('bpd_abandonment', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Страх брошенности (0-1)'),
    sa.Column('bpd_unstable_relations', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Нестабильные отношения (0-1)'),
    sa.Column('bpd_identity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Нарушение идентичности (0-1)'),
    sa.Column('bpd_impulsivity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Импульсивность (0-1)'),
    sa.Column('bpd_suicidal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Суицидальное поведение (0-1)'),
    sa.Column('bpd_mood_swings', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Перепады настроения (0-1)'),
    sa.Column('bpd_emptiness', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Чувство пустоты (0-1)'),
    sa.Column('bpd_anger', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Неадекватный гнев (0-1)'),
    sa.Column('bpd_paranoia', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Параноидные идеи (0-1)'),
    sa.Column('npd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Нарциссическое РЛ (0-1)'),
    sa.Column('aspd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Антисоциальное РЛ (0-1)'),
    sa.Column('avpd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Избегающее РЛ (0-1)'),
    sa.Column('dpd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Зависимое РЛ (0-1)'),
    sa.Column('ocpd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Обсессивно-компульсивное РЛ (0-1)'),
    sa.Column('ppd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Параноидное РЛ (0-1)'),
    sa.Column('szpd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Шизоидное РЛ (0-1)'),
    sa.Column('stpd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Шизотипическое РЛ (0-1)'),
    sa.Column('accuracy_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='процент точности'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('personality_disorders_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('personality_disorders_pkey'))
    )
    op.create_table('mood_disorders',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False, comment='ID пользователя'),
    sa.Column('depression', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Уровень депрессии (0-1)'),
    sa.Column('depression_sadness', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Грусть (0-1)'),
    sa.Column('depression_anhedonia', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Ангедония (0-1)'),
    sa.Column('depression_appetite', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Нарушение аппетита (0-1)'),
    sa.Column('depression_sleep', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Нарушения сна (0-1)'),
    sa.Column('depression_fatigue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Усталость (0-1)'),
    sa.Column('depression_worthlessness', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Чувство никчемности (0-1)'),
    sa.Column('depression_concentration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Нарушения концентрации (0-1)'),
    sa.Column('depression_suicidal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Суицидальные мысли (0-1)'),
    sa.Column('bipolar', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Биполярное расстройство (0-1)'),
    sa.Column('bipolar_mania', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Маниакальные эпизоды (0-1)'),
    sa.Column('bipolar_hypomania', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Гипоманиакальные эпизоды (0-1)'),
    sa.Column('bipolar_depression', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Депрессивные эпизоды (0-1)'),
    sa.Column('bipolar_rapid', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Быстрая смена фаз (0-1)'),
    sa.Column('bipolar_psychotic', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Психотические черты (0-1)'),
    sa.Column('cyclothymia', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Циклотимия (0-1)'),
    sa.Column('accuracy_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='процент точности'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('mood_disorders_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('mood_disorders_pkey'))
    )
    op.drop_index(op.f('ix_ptsd_disorder_user_id'), table_name='ptsd_disorder')
    op.drop_table('ptsd_disorder')
    op.drop_index(op.f('ix_panic_disorder_user_id'), table_name='panic_disorder')
    op.drop_table('panic_disorder')
    op.drop_table('looks_disorder')
    op.drop_index(op.f('ix_gdr_disorder_user_id'), table_name='gdr_disorder')
    op.drop_table('gdr_disorder')
    op.drop_index(op.f('ix_eating_disorder_user_id'), table_name='eating_disorder')
    op.drop_table('eating_disorder')
    op.drop_index(op.f('ix_dissociative_disorder_user_id'), table_name='dissociative_disorder')
    op.drop_table('dissociative_disorder')
    op.drop_index(op.f('ix_depression_disorder_user_id'), table_name='depression_disorder')
    op.drop_table('depression_disorder')
    op.drop_table('bpd_disorder')
    op.drop_index(op.f('ix_bipolar_disorder_user_id'), table_name='bipolar_disorder')
    op.drop_table('bipolar_disorder')
    op.drop_index(op.f('ix_autism_disorder_user_id'), table_name='autism_disorder')
    op.drop_table('autism_disorder')
    op.drop_table('adhd_disorder')
    # ### end Alembic commands ###
