"""empty message

Revision ID: 494d63dacf1b
Revises: 89a8daba2ba3
Create Date: 2026-03-24 21:46:52.267101

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '494d63dacf1b'
down_revision = '89a8daba2ba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'talk_mode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('talk_mode', postgresql.ENUM('research', 'psycho', name='talking_modes'), server_default=sa.text("'research'::talking_modes"), autoincrement=False, nullable=False, comment='режим общения'))
    # ### end Alembic commands ###
