"""empty message

Revision ID: 4a24ec33f344
Revises: 494d63dacf1b
Create Date: 2026-03-27 16:39:41.796466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a24ec33f344'
down_revision = '494d63dacf1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passed_typing', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='типирование пройдено'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'passed_typing')
    # ### end Alembic commands ###
