"""empty message

Revision ID: 532782575b86
Revises: 4a24ec33f344
Create Date: 2026-03-27 20:52:40.140295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '532782575b86'
down_revision = '4a24ec33f344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('real_name', sa.String(), nullable=True, comment='реальное имя'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'real_name')
    # ### end Alembic commands ###
