"""empty message

Revision ID: 600ef80872c0
Revises: 25e53c59ffb0
Create Date: 2026-02-23 00:54:45.231700

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '600ef80872c0'
down_revision = '25e53c59ffb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_socionics', sa.Column('ENTP', sa.Float(), nullable=True, comment='ENTP / ILE – Intuitive Logical Extravert (Don Quixote)'))
    op.add_column('user_socionics', sa.Column('ISFJ', sa.Float(), nullable=True, comment='ISFJ / SEI – Sensing Ethical Introvert (Dumas)'))
    op.add_column('user_socionics', sa.Column('ESFJ', sa.Float(), nullable=True, comment='ESFJ / ESE – Ethical Sensory Extravert (Hugo)'))
    op.add_column('user_socionics', sa.Column('INTP', sa.Float(), nullable=True, comment='INTP / LII – Logical Intuitive Introvert (Robespierre)'))
    op.add_column('user_socionics', sa.Column('ENFJ', sa.Float(), nullable=True, comment='ENFJ / EIE – Ethical Intuitive Extravert (Hamlet)'))
    op.add_column('user_socionics', sa.Column('ISTP', sa.Float(), nullable=True, comment='ISTP / LSI – Logical Sensory Introvert (Maxim Gorky)'))
    op.add_column('user_socionics', sa.Column('ESTP', sa.Float(), nullable=True, comment='ESTP / SLE – Sensory Logical Extravert (Zhukov)'))
    op.add_column('user_socionics', sa.Column('INFJ', sa.Float(), nullable=True, comment='INFJ / IEI – Intuitive Ethical Introvert (Yesenin)'))
    op.add_column('user_socionics', sa.Column('ESFP', sa.Float(), nullable=True, comment='ESFP / SEE – Sensory Ethical Extravert (Napoleon)'))
    op.add_column('user_socionics', sa.Column('INTJ', sa.Float(), nullable=True, comment='INTJ / ILI – Intuitive Logical Introvert (Balzac)'))
    op.add_column('user_socionics', sa.Column('ENTJ', sa.Float(), nullable=True, comment='ENTJ / LIE – Logical Intuitive Extravert (Jack London)'))
    op.add_column('user_socionics', sa.Column('ISFP', sa.Float(), nullable=True, comment='ISFP / ESI – Ethical Sensory Introvert (Dreiser)'))
    op.add_column('user_socionics', sa.Column('ENFP', sa.Float(), nullable=True, comment='ENFP / IEE – Intuitive Ethical Extravert (Huxley)'))
    op.add_column('user_socionics', sa.Column('INFP', sa.Float(), nullable=True, comment='INFP / EII – Ethical Intuitive Introvert (Dostoevsky)'))
    op.add_column('user_socionics', sa.Column('ESTJ', sa.Float(), nullable=True, comment='ESTJ / LSE – Logical Sensory Extravert (Stirlitz)'))
    op.add_column('user_socionics', sa.Column('ISTJ', sa.Float(), nullable=True, comment='ISTJ / SLI – Sensory Logical Introvert (Gabin)'))
    op.drop_column('user_socionics', 'socionics_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_socionics', sa.Column('socionics_type', postgresql.ENUM('ИЛЭ', 'СЭИ', 'ЭСЭ', 'ЛИИ', 'СЛЭ', 'ИЭИ', 'ЭИЭ', 'ЛСИ', 'СЭЭ', 'ИЛИ', 'ЛИЭ', 'ЭСИ', 'ЛСЭ', 'ЭИИ', 'ИЭЭ', 'СЛИ', name='socionics_type'), autoincrement=False, nullable=True))
    op.drop_column('user_socionics', 'ISTJ')
    op.drop_column('user_socionics', 'ESTJ')
    op.drop_column('user_socionics', 'INFP')
    op.drop_column('user_socionics', 'ENFP')
    op.drop_column('user_socionics', 'ISFP')
    op.drop_column('user_socionics', 'ENTJ')
    op.drop_column('user_socionics', 'INTJ')
    op.drop_column('user_socionics', 'ESFP')
    op.drop_column('user_socionics', 'INFJ')
    op.drop_column('user_socionics', 'ESTP')
    op.drop_column('user_socionics', 'ISTP')
    op.drop_column('user_socionics', 'ENFJ')
    op.drop_column('user_socionics', 'INTP')
    op.drop_column('user_socionics', 'ESFJ')
    op.drop_column('user_socionics', 'ISFJ')
    op.drop_column('user_socionics', 'ENTP')
    # ### end Alembic commands ###
