"""empty message

Revision ID: 89a8daba2ba3
Revises: 46aac306e58b
Create Date: 2026-03-21 18:25:31.691867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a8daba2ba3'
down_revision = '46aac306e58b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_profiles', sa.Column('cooperativity', sa.Float(), nullable=True, comment='Кооперативность'))
    op.alter_column('social_profiles', 'competitiveness',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Соревновательность',
               existing_comment='0=кооперативный, 1=соревновательный',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('social_profiles', 'competitiveness',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='0=кооперативный, 1=соревновательный',
               existing_comment='Соревновательность',
               existing_nullable=True)
    op.drop_column('social_profiles', 'cooperativity')
    # ### end Alembic commands ###
