"""empty message

Revision ID: 9db6068cbf52
Revises: 532782575b86
Create Date: 2026-03-30 15:06:07.389876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9db6068cbf52'
down_revision = '532782575b86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('talk_mode', sa.Enum('research', 'psycho', name='talking_modes'), server_default='research', nullable=False, comment='режим общения'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'talk_mode')
    # ### end Alembic commands ###
