"""empty message

Revision ID: ce05aa31192f
Revises: 352ed5d627f2
Create Date: 2026-02-15 11:32:38.466436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce05aa31192f'
down_revision = '352ed5d627f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_diary_one_per_day', 'user_diary', ['user_id', 'created_at'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_diary_one_per_day', 'user_diary', type_='unique')
    # ### end Alembic commands ###
