"""empty message

Revision ID: d4df46d8b9fb
Revises: 423e44b7e415
Create Date: 2026-02-13 01:16:35.873229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4df46d8b9fb'
down_revision = '423e44b7e415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_humor_sense', sa.Column('dominant_humor', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_humor_sense', 'dominant_humor')
    # ### end Alembic commands ###
