"""empty message

Revision ID: f069ce41d276
Revises: 600ef80872c0
Create Date: 2026-02-23 22:43:18.812014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f069ce41d276'
down_revision = '600ef80872c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_socionics', sa.Column('records', sa.Integer(), nullable=False, comment='количество записей'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_socionics', 'records')
    # ### end Alembic commands ###
